### ISSUE TITLE
login logout issue

### ISSUE THREAD

**Issue by iluuuk** [webtechnick/CakePHP-Facebook-Plugin#23]
Hi,

I just realized your website doesn't work properly. I'm not able to login to see "myaccount", i always see the login button. The first time i got the permissions request, but after that i still can't see "myaccount".

I have a similar problem in my application. I followed your screencast and the svn app. I can log in, i. e., when i login via facebook, i can see "myaccount". The problem is, when i click logout, i only exit the facebook session, but i can still see myaccount... any help?

Maybe the my app's advanced configs have somthing to do...

Running Mac OS X Lion
with Chrome 13.0.782.99 beta
from Facebook iFrame Canvas @ php sdk 3.1.1

**Comment by webtechnick** [comment]
This has been resolved.  Thank you for letting me know.

**Comment by iluuuk** [comment]
I'm sorry, but facebook and cakephp login systems are still not properly coupled. Now I can access myaccount, but when i sign out, I can still access myaccount. So Auth user is not logged out.

Thanks for your time & plugin

**Comment by tspesh** [comment]
I'm seeing the same behavior.  Something is regenerating the fbsr_{app ID} cookie...

**Comment by andreirebe** [comment]
This issue should be reopened. I have the same problem.

**Comment by styks1111** [comment]
Same problem

**Comment by styks1111** [comment]
I think I was able to get around this by doing this

``` php
    $this->Auth->logout();
    $this->Session->setFlash('Good-Bye');
    $this->redirect('/');
```

Instead of this

``` php
     $this->Session->setFlash('Good-Bye');
     $this->redirect($this->Auth->logout()):
```
